version: '3.8'

services:
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - ${PORT}

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./packages/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./packages/caddy/log:/var/log/caddy

volumes:
  caddy_data:
  caddy_config:
