name: Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: 'SOME_API_KEY'
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Sync code to server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i --delete'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: ${{ secrets.SSH_TARGER_FOLDER }}
          SCRIPT_AFTER: |
            cd ./lottery
