name: Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@master
        with:
          since_last_remote_commit: true
          separator: ','

      - name: Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: ${{ secrets.SSH_TARGER_FOLDER }}

      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 30m
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd lottery && ls -al
